### ISSUE TITLE
Data/NLTK/corpora questions

### ISSUE THREAD

**Issue by bhargavvader** [Computational-Content-Analysis-2020/frequently-asked-questions#3]
Hello friends,

Please post issues regarding downloading and accessing data here. 
Also regarding resources for corpora.

**Comment by bjcliang-uchi** [comment]
HW1 uses Shakespeare data. I can't find it in corpora or data

**Comment by bhargavvader** [comment]
Running ```nltk.download()``` should fix that.

**Comment by sanittawan** [comment]
That still doesn't work for me. 

Here's the error message:

FileNotFoundError: [Errno 2] No such file or directory: '../data/Shakespeare/midsummer_nights_dream.txt'

I ran nltk.download() and saw this "[nltk_data]    | Downloading package shakespeare to ../data..." though.

**Comment by bhargavvader** [comment]
I see... Ok, I've manually downloaded and added the Shakespeare data.
Running ```git pull base master``` will get you the latest version of the repository. This should have the data.

**Comment by Dominiquo** [comment]
@bhargavvader How do we access the corpora shared in class on Friday?

**Comment by bhargavvader** [comment]
Hello @Dominiquo I'm in the process of making it easy to access for ya'll!

**Comment by wunicoleshuhui** [comment]
On HW3 right after inputting the first cell, there 's a error for "module 'lucem_illud_2020' has no attribute 'trainTestSplit'"

**Comment by skanthan95** [comment]
Having the same problem as @wunicoleshuhui  (after running "git pull base master", running the code to update our machines each week, and restarting the notebook)

**Comment by bhargavvader** [comment]
This is so annoying/strange - it seems to be something to do with Jupyter notebook not recognising the latest update. I would say use the RCC now, while I try and figure it out.

I do think that just uninstalling everything (including Jupyter/Conda) and reinstalling it should fix it though...

**Comment by heathercchen** [comment]
@bhargavvader Hi Bhargav! How can we get access to the corpora shared by Prof. Evans? I think I may need to have access to these data for my future homework... Sorry for the trouble!

**Comment by bhargavvader** [comment]
@heathercchen working on it as we speak - you'll have a Jupyter notebook on instructions on how to access it on RCC as well as have the functionality on ```lucem_illud_2020```. Latest by... tomorrow night!
